@url = http://127.0.0.1:8005
@access = abc
@refresh = 

###
POST {{url}}/authorization
Content-Type: application/json

{
  "authorizationCode": "oGG2yKhnE4f7rjhYvqSvsS1AwViRjq0tNwPBnwn7hfPTz2YjSI7Z6XJ4HVQXOH3uYaODSdRkDW98DmGycYTdEA9yXVosWJPEI71zURiiERZDLGYDj1QyZBqwlBAaOpGt",
  "codeVerifier": "tpWFpflpskMgYA"
}

###
POST {{url}}/refresh
Content-Type: application/json
Cookie: refreshToken={{refresh}};

{}

### first verify then refresh
POST {{url}}/refresh
Content-Type: application/json
Cookie: accessToken={{access}}; refreshToken={{refresh}};

{
  "action": "chat",
  "modelId": "1"
}
