@url = http://127.0.0.1:8005
@token = 

###
POST {{url}}/chat
Content-Type: application/json
Cookie: accessToken={{token}}

{
    "modelId": 2,
    "sessionId": "abc",
    "messages": [
        {
            "role": "user",
            "content": "say hi, don't say others"
        }
    ]
}
